version: '3.7'
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    hostname: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/Chicago
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=false
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_NOTIFICATIONS=slack
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=https://hooks.slack.com/services/xxx/yyyyyyyyyyyyyyy
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=Watchtower
      - WATCHTOWER_NOTIFICATION_SLACK_CHANNEL=#general
      - WATCHTOWER_NOTIFICATION_SLACK_ICON_EMOJI=:whale:
      - WATCHTOWER_NOTIFICATION_SLACK_ICON_URL=https://github.com/containrrr/watchtower/raw/master/logo.png
    labels:
      # Traefik Labels
      - "traefik.enable=true"
      # HTTPS Labels
      - "traefik.http.routers.watchtower.rule=Host(`localhost`)" # Domain Name
      - "traefik.http.routers.watchtower.entrypoints=web-secure"
      - "traefik.http.routers.watchtower.middlewares=default-headers@file"
      - "traefik.http.routers.watchtower.service=watchtower"
      - "traefik.http.routers.watchtower.tls=true"
      - "traefik.http.services.watchtower.loadbalancer.server.port=80" # Proxied Port
